## Option for M5stack SCD41, CO2, humidity and temperature sensor on i2c bus. I2C must be enabled.
sensor:
  - platform: scd4x
    co2:
      name: ${brink_co2_from_inside}
      id: brink_co2_from_inside
        humidity:
          name: ${brink_humidity_from_inside}
          id: brink_humidity_from_inside
        temperature:
          name: ${brink_temp_from_inside}
          id: brink_temp_from_inside
        temperature_offset: "4.2°C"
        measurement_mode: low_power_periodic
    i2c_id: bus_b
    address: 0x62
    update_interval: 30s
# Performance now can be calculated with the extra temperature sensor.
 - id: brink_performance
   name: ${brink_performance}
   platform: template
   unit_of_measurement: "%"
   update_interval: 30s
   lambda: 'return ((id(brink_temp_to_inside).state - id(brink_temp_from_outside).state)/(id(brink_temp_from_inside).state - id(brink_temp_from_outside).state)*100);'
(temp_to_inside - temp_from_outside) / (temp_from_inside - temp_from_outside)
